<?php 
require("header.php");
require("./Menu/menu.php");
require("./Tiempo/tiempo.php");
require("./About/about.php");
require("./Team/team.php");
require("./Plan/plan.php");
require("./Espacio/espacio.php");
require("./Patrocinadores/patro.php");
require("footer.php");
